-- MySQL Script generated by MySQL Workbench
-- mar 23 mar 2021 09:52:10 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `pdata` TINYINT NOT NULL,
  `rol` TINYINT NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`houses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`houses` (
  `idhouses` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `num_rooms` VARCHAR(45) NOT NULL,
  `num_toilets` VARCHAR(45) NOT NULL,
  `parking_lot` TINYINT NULL,
  `internet` TINYINT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idhouses`, `users_idusers`),
  INDEX `fk_houses_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_houses_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bookings` (
  `idBookings` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `final_date` DATE NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idBookings`, `users_idusers`),
  INDEX `fk_Bookings_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_Bookings_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `idimages` INT NOT NULL AUTO_INCREMENT,
  `imgp` VARCHAR(45) NULL,
  `imgs` VARCHAR(45) NULL,
  `houses_idhouses` INT NOT NULL,
  PRIMARY KEY (`idimages`, `houses_idhouses`),
  INDEX `fk_images_houses1_idx` (`houses_idhouses` ASC) VISIBLE,
  CONSTRAINT `fk_images_houses1`
    FOREIGN KEY (`houses_idhouses`)
    REFERENCES `mydb`.`houses` (`idhouses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`houses_has_Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`houses_has_Bookings` (
  `houses_idhouses` INT NOT NULL,
  `Bookings_idBookings` INT NOT NULL,
  PRIMARY KEY (`houses_idhouses`, `Bookings_idBookings`),
  INDEX `fk_houses_has_Bookings_Bookings1_idx` (`Bookings_idBookings` ASC) VISIBLE,
  INDEX `fk_houses_has_Bookings_houses1_idx` (`houses_idhouses` ASC) VISIBLE,
  CONSTRAINT `fk_houses_has_Bookings_houses1`
    FOREIGN KEY (`houses_idhouses`)
    REFERENCES `mydb`.`houses` (`idhouses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_houses_has_Bookings_Bookings1`
    FOREIGN KEY (`Bookings_idBookings`)
    REFERENCES `mydb`.`Bookings` (`idBookings`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`additional_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`additional_services` (
  `idadditional_services` INT NOT NULL AUTO_INCREMENT,
  `service` VARCHAR(45) NULL,
  `houses_idhouses` INT NOT NULL,
  `houses_users_idusers` INT NOT NULL,
  PRIMARY KEY (`idadditional_services`, `houses_idhouses`, `houses_users_idusers`),
  INDEX `fk_additional_services_houses1_idx` (`houses_idhouses` ASC, `houses_users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_additional_services_houses1`
    FOREIGN KEY (`houses_idhouses` , `houses_users_idusers`)
    REFERENCES `mydb`.`houses` (`idhouses` , `users_idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
