<<<<<<< HEAD
=======
-- MySQL Script generated by MySQL Workbench
-- jue 25 mar 2021 15:02:23 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(45) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password_user` VARCHAR(256) NOT NULL,
  `city` VARCHAR(70) NOT NULL,
  `pdata` TINYINT NOT NULL,
  `rol` TINYINT NOT NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `houses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houses` (
  `idhouses` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `num_rooms` INT NOT NULL,
  `num_toilets` INT NOT NULL,
  `parking_lot` TINYINT NULL,
  `internet` TINYINT NULL,
  `users_idusers` INT NOT NULL,
  `price_pn` FLOAT NOT NULL,
  PRIMARY KEY (`idhouses`),
  INDEX `fk_houses_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_houses_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookings` (
  `idBookings` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `final_date` DATE NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idBookings`),
  INDEX `fk_Bookings_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_Bookings_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `images` (
  `idimages` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(256) NULL,
  `main` TINYINT NULL,
  `houses_idhouses` INT NOT NULL,
  PRIMARY KEY (`idimages`),
  INDEX `fk_images_houses1_idx` (`houses_idhouses` ASC),
  CONSTRAINT `fk_images_houses1`
    FOREIGN KEY (`houses_idhouses`)
    REFERENCES `houses` (`idhouses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `houses_has_Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houses_has_Bookings` (
  `houses_idhouses` INT NOT NULL,
  `Bookings_idBookings` INT NOT NULL,
  PRIMARY KEY (`houses_idhouses`, `Bookings_idBookings`),
  INDEX `fk_houses_has_Bookings_Bookings1_idx` (`Bookings_idBookings` ASC),
  INDEX `fk_houses_has_Bookings_houses1_idx` (`houses_idhouses` ASC),
  CONSTRAINT `fk_houses_has_Bookings_houses1`
    FOREIGN KEY (`houses_idhouses`)
    REFERENCES `houses` (`idhouses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_houses_has_Bookings_Bookings1`
    FOREIGN KEY (`Bookings_idBookings`)
    REFERENCES `Bookings` (`idBookings`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `additional_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `additional_services` (
  `idadditional_services` INT NOT NULL AUTO_INCREMENT,
  `service` VARCHAR(100) NULL,
  PRIMARY KEY (`idadditional_services`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `houses_has_additional_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houses_has_additional_services` (
  `houses_idhouses` INT NOT NULL,
  `idadditional_services` INT NOT NULL,
  PRIMARY KEY (`houses_idhouses`, `idadditional_services`),
  INDEX `fk_houses_has_additional_services_additional_services1_idx` (`idadditional_services` ASC),
  INDEX `fk_houses_has_additional_services_houses1_idx` (`houses_idhouses` ASC),
  CONSTRAINT `fk_houses_has_additional_services_houses1`
    FOREIGN KEY (`houses_idhouses`)
    REFERENCES `houses` (`idhouses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_houses_has_additional_services_additional_services1`
    FOREIGN KEY (`idadditional_services`)
    REFERENCES `additional_services` (`idadditional_services`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
>>>>>>> 8790b4c224213ccec653345d8f9f4e2b701b822e
-- MySQL dump 10.13  Distrib 8.0.23, for Win64 (x86_64)
--
-- Host: 127.0.0.1    Database: hotelp2
-- ------------------------------------------------------
-- Server version	8.0.23

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `bookings`
--  

DROP TABLE IF EXISTS `bookings`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `bookings` (
  `idBooking` int NOT NULL AUTO_INCREMENT,
  `houses` int NOT NULL,
  `users` int NOT NULL,
  `datestart` date DEFAULT NULL,
  `datefinish` date DEFAULT NULL,
  PRIMARY KEY (`idBooking`),
  KEY `houses` (`houses`),
  KEY `users` (`users`),
  CONSTRAINT `bookings_ibfk_1` FOREIGN KEY (`houses`) REFERENCES `houses` (`idhouse`),
  CONSTRAINT `bookings_ibfk_2` FOREIGN KEY (`users`) REFERENCES `users` (`iduser`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `bookings`
--

LOCK TABLES `bookings` WRITE;
/*!40000 ALTER TABLE `bookings` DISABLE KEYS */;
/*!40000 ALTER TABLE `bookings` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `houses`
--

DROP TABLE IF EXISTS `houses`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `houses` (
  `idhouse` int NOT NULL AUTO_INCREMENT,
  `users` int NOT NULL,
  `title` varchar(50) DEFAULT NULL,
  `description_house` varchar(200) DEFAULT NULL,
  `price` int DEFAULT NULL,
  `image_p` varchar(256) DEFAULT NULL,
  `images` varchar(256) DEFAULT NULL,
  `num_rooms` int DEFAULT NULL,
  `num_toilets` int DEFAULT NULL,
  `parking_lot` tinyint(1) DEFAULT NULL,
  `internet` tinyint(1) DEFAULT NULL,
  `additional_services` int DEFAULT NULL,
  PRIMARY KEY (`idhouse`),
  KEY `users` (`users`),
  KEY `additional_services` (`additional_services`),
  CONSTRAINT `houses_ibfk_1` FOREIGN KEY (`users`) REFERENCES `users` (`iduser`),
  CONSTRAINT `houses_ibfk_2` FOREIGN KEY (`additional_services`) REFERENCES `services` (`idservice`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `houses`
--

LOCK TABLES `houses` WRITE;
/*!40000 ALTER TABLE `houses` DISABLE KEYS */;
/*!40000 ALTER TABLE `houses` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `image`
--

DROP TABLE IF EXISTS `image`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `image` (
  `idimage` int NOT NULL AUTO_INCREMENT,
  `houses` int NOT NULL,
  `image` varchar(256) DEFAULT NULL,
  `type_image` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`idimage`),
  KEY `houses` (`houses`),
  CONSTRAINT `image_ibfk_1` FOREIGN KEY (`houses`) REFERENCES `houses` (`idhouse`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `image`
--

LOCK TABLES `image` WRITE;
/*!40000 ALTER TABLE `image` DISABLE KEYS */;
/*!40000 ALTER TABLE `image` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `services`
--

DROP TABLE IF EXISTS `services`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `services` (
  `idservice` int NOT NULL AUTO_INCREMENT,
  `houses` int NOT NULL,
  `service` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`idservice`),
  KEY `houses` (`houses`),
  CONSTRAINT `services_ibfk_1` FOREIGN KEY (`houses`) REFERENCES `houses` (`idhouse`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `services`
--

LOCK TABLES `services` WRITE;
/*!40000 ALTER TABLE `services` DISABLE KEYS */;
/*!40000 ALTER TABLE `services` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `users` (
  `iduser` int NOT NULL AUTO_INCREMENT,
  `name_user` varchar(50) DEFAULT NULL,
  `email` varchar(256) DEFAULT NULL,
  `password_user` varchar(256) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  `rol` tinyint(1) DEFAULT NULL,
  `pdata` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`iduser`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `users`
--

LOCK TABLES `users` WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` VALUES (1,'David M','davidmx755@hotmail.com','e10adc3949ba59abbe56e057f20f883e','Soacha',1,1);
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
alter table Bookings add total float;
alter table Bookings drop houseId;
ALTER TABLE Bookings
ADD FOREIGN KEY(houseId) REFERENCES houses(idhouses);
-- Dump completed on 2021-03-23 22:32:27
