-- MySQL Script generated by MySQL Workbench
-- jue 25 mar 2021 15:02:23 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(45) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password_user` VARCHAR(256) NOT NULL,
  `city` VARCHAR(70) NOT NULL,
  `pdata` TINYINT NOT NULL,
  `rol` TINYINT NOT NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `houses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houses` (
  `idhouses` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `num_rooms` INT NOT NULL,
  `num_toilets` INT NOT NULL,
  `parking_lot` TINYINT NULL,
  `internet` TINYINT NULL,
  `users_idusers` INT NOT NULL,
  `price_pn` FLOAT NOT NULL,
  PRIMARY KEY (`idhouses`),
  INDEX `fk_houses_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_houses_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookings` (
  `idBookings` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `final_date` DATE NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idBookings`),
  INDEX `fk_Bookings_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_Bookings_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `images` (
  `idimages` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(256) NULL,
  `main` TINYINT NULL,
  `houses_idhouses` INT NOT NULL,
  PRIMARY KEY (`idimages`),
  INDEX `fk_images_houses1_idx` (`houses_idhouses` ASC),
  CONSTRAINT `fk_images_houses1`
    FOREIGN KEY (`houses_idhouses`)
    REFERENCES `houses` (`idhouses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `houses_has_Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houses_has_Bookings` (
  `houses_idhouses` INT NOT NULL,
  `Bookings_idBookings` INT NOT NULL,
  PRIMARY KEY (`houses_idhouses`, `Bookings_idBookings`),
  INDEX `fk_houses_has_Bookings_Bookings1_idx` (`Bookings_idBookings` ASC),
  INDEX `fk_houses_has_Bookings_houses1_idx` (`houses_idhouses` ASC),
  CONSTRAINT `fk_houses_has_Bookings_houses1`
    FOREIGN KEY (`houses_idhouses`)
    REFERENCES `houses` (`idhouses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_houses_has_Bookings_Bookings1`
    FOREIGN KEY (`Bookings_idBookings`)
    REFERENCES `Bookings` (`idBookings`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `additional_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `additional_services` (
  `idadditional_services` INT NOT NULL AUTO_INCREMENT,
  `service` VARCHAR(100) NULL,
  PRIMARY KEY (`idadditional_services`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `houses_has_additional_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houses_has_additional_services` (
  `houses_idhouses` INT NOT NULL,
  `idadditional_services` INT NOT NULL,
  PRIMARY KEY (`houses_idhouses`, `idadditional_services`),
  INDEX `fk_houses_has_additional_services_additional_services1_idx` (`idadditional_services` ASC),
  INDEX `fk_houses_has_additional_services_houses1_idx` (`houses_idhouses` ASC),
  CONSTRAINT `fk_houses_has_additional_services_houses1`
    FOREIGN KEY (`houses_idhouses`)
    REFERENCES `houses` (`idhouses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_houses_has_additional_services_additional_services1`
    FOREIGN KEY (`idadditional_services`)
    REFERENCES `additional_services` (`idadditional_services`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;